// 이 파일은 tools/generate_game_data.py 가 원본 패키지에서 생성했다.
// 직접 고치지 말고 생성기를 고칠 것.

/** 투수 레코드 — 폼 니블(+0xb>>4), 마구 번호(+0x18, 0 = 없음), 보유 구질 비트마스크(+0x1c, 비트 t−1 = 구질 t) */
export interface PitcherRepertoire {
  readonly name: string
  readonly form: number
  readonly magicId: number
  readonly pitchMask: number
}

export const ACE_PITCHER_REPERTOIRES: readonly PitcherRepertoire[] = [
  { name: '싸이커', form: 6, magicId: 5, pitchMask: 16651 },
  { name: '레오니', form: 7, magicId: 6, pitchMask: 66129 },
  { name: '붕붕머신', form: 8, magicId: 7, pitchMask: 3233 },
  { name: '발렌타인', form: 9, magicId: 8, pitchMask: 1048653 },
  { name: '드래고나', form: 10, magicId: 9, pitchMask: 692225 },
]

export const ROSTER_PITCHER_REPERTOIRES: readonly PitcherRepertoire[] = [
  { name: '봉은중', form: 1, magicId: 0, pitchMask: 4419 },
  { name: '심수찬', form: 0, magicId: 0, pitchMask: 177 },
  { name: '김광순', form: 0, magicId: 0, pitchMask: 305 },
  { name: '정만복', form: 0, magicId: 0, pitchMask: 195 },
  { name: '류택근', form: 1, magicId: 0, pitchMask: 16657 },
  { name: '정찬호', form: 0, magicId: 0, pitchMask: 73 },
  { name: '우규만', form: 4, magicId: 0, pitchMask: 297 },
  { name: '이재형', form: 0, magicId: 0, pitchMask: 609 },
  { name: '신선우', form: 0, magicId: 0, pitchMask: 307 },
  { name: '홍산삼', form: 0, magicId: 0, pitchMask: 32779 },
  { name: '김상연', form: 0, magicId: 0, pitchMask: 305 },
  { name: '정재현', form: 0, magicId: 0, pitchMask: 149 },
  { name: '고찬성', form: 4, magicId: 0, pitchMask: 331 },
  { name: '이재호', form: 0, magicId: 0, pitchMask: 297 },
  { name: '임대훈', form: 0, magicId: 0, pitchMask: 107 },
  { name: '이영창', form: 0, magicId: 0, pitchMask: 197 },
  { name: '김광연', form: 1, magicId: 0, pitchMask: 8961 },
  { name: '송승범', form: 0, magicId: 0, pitchMask: 341 },
  { name: '고호준', form: 1, magicId: 0, pitchMask: 16515 },
  { name: '채상용', form: 0, magicId: 0, pitchMask: 297 },
  { name: '안우람', form: 1, magicId: 0, pitchMask: 329 },
  { name: '전병도', form: 1, magicId: 0, pitchMask: 16905 },
  { name: '이승후', form: 1, magicId: 0, pitchMask: 65585 },
  { name: '정태현', form: 4, magicId: 0, pitchMask: 32811 },
  { name: '류현준', form: 1, magicId: 0, pitchMask: 67653 },
  { name: '유원성', form: 0, magicId: 0, pitchMask: 337 },
  { name: '안영민', form: 0, magicId: 0, pitchMask: 809 },
  { name: '김민혁', form: 0, magicId: 0, pitchMask: 329 },
  { name: '양준', form: 0, magicId: 0, pitchMask: 297 },
  { name: '구대선', form: 1, magicId: 0, pitchMask: 16517 },
  { name: '마정일', form: 4, magicId: 0, pitchMask: 329 },
  { name: '토머스', form: 1, magicId: 0, pitchMask: 209 },
  { name: '윤정환', form: 0, magicId: 0, pitchMask: 307 },
  { name: '프란시스', form: 0, magicId: 0, pitchMask: 16531 },
  { name: '차수찬', form: 1, magicId: 0, pitchMask: 337 },
  { name: '배열수', form: 0, magicId: 0, pitchMask: 171 },
  { name: '원혁', form: 1, magicId: 0, pitchMask: 181 },
  { name: '정현종', form: 0, magicId: 0, pitchMask: 331 },
  { name: '안지민', form: 0, magicId: 0, pitchMask: 201 },
  { name: '오수환', form: 0, magicId: 0, pitchMask: 77 },
  { name: '윤석인', form: 0, magicId: 0, pitchMask: 4801 },
  { name: '호세', form: 0, magicId: 0, pitchMask: 171 },
  { name: '톰슨', form: 0, magicId: 0, pitchMask: 809 },
  { name: '양현중', form: 1, magicId: 0, pitchMask: 331 },
  { name: 'TiTo', form: 0, magicId: 0, pitchMask: 1065 },
  { name: '서재웅', form: 0, magicId: 0, pitchMask: 339 },
  { name: '한기준', form: 0, magicId: 0, pitchMask: 197 },
  { name: '오동훈', form: 4, magicId: 0, pitchMask: 331 },
  { name: '손민환', form: 0, magicId: 0, pitchMask: 2371 },
  { name: '조정헌', form: 0, magicId: 0, pitchMask: 205 },
  { name: '송승훈', form: 0, magicId: 0, pitchMask: 163 },
  { name: '장원주', form: 1, magicId: 0, pitchMask: 817 },
  { name: '강영신', form: 1, magicId: 0, pitchMask: 305 },
  { name: '임경원', form: 2, magicId: 0, pitchMask: 16649 },
  { name: '이정후', form: 0, magicId: 0, pitchMask: 201 },
  { name: '위킨스', form: 0, magicId: 0, pitchMask: 593 },
  { name: '이현성', form: 1, magicId: 0, pitchMask: 301 },
  { name: '마인영', form: 1, magicId: 0, pitchMask: 1064977 },
  { name: '김수겸', form: 0, magicId: 0, pitchMask: 299 },
  { name: '정원삼', form: 1, magicId: 0, pitchMask: 211 },
  { name: '송진영', form: 0, magicId: 0, pitchMask: 337 },
  { name: '신철민', form: 0, magicId: 0, pitchMask: 16649 },
  { name: '이보군', form: 0, magicId: 0, pitchMask: 163 },
  { name: '황토성', form: 0, magicId: 0, pitchMask: 325 },
  { name: '최재호', form: 1, magicId: 0, pitchMask: 1361 },
  { name: '강건희', form: 0, magicId: 0, pitchMask: 681 },
  { name: '홍승민', form: 2, magicId: 0, pitchMask: 205 },
  { name: '홍경순', form: 3, magicId: 0, pitchMask: 339 },
  { name: '김성민', form: 4, magicId: 0, pitchMask: 43 },
  { name: '이상범', form: 5, magicId: 0, pitchMask: 337 },
  { name: '김대홍', form: 0, magicId: 0, pitchMask: 165 },
  { name: '김성준', form: 1, magicId: 0, pitchMask: 32845 },
  { name: '정일호', form: 2, magicId: 0, pitchMask: 16533 },
  { name: '장수통', form: 0, magicId: 0, pitchMask: 299 },
  { name: '유한동', form: 3, magicId: 0, pitchMask: 329 },
  { name: '손지명', form: 4, magicId: 0, pitchMask: 211 },
  { name: '조커최', form: 2, magicId: 0, pitchMask: 293 },
  { name: '장상규', form: 1, magicId: 0, pitchMask: 203 },
  { name: '폴리연진', form: 2, magicId: 0, pitchMask: 329 },
  { name: '박수빈', form: 5, magicId: 0, pitchMask: 173 },
  { name: '봉은중', form: 1, magicId: 0, pitchMask: 4419 },
  { name: '류현준', form: 1, magicId: 0, pitchMask: 67653 },
  { name: '윤석인', form: 0, magicId: 0, pitchMask: 4801 },
  { name: '김광연', form: 1, magicId: 0, pitchMask: 8961 },
  { name: '정현종', form: 0, magicId: 0, pitchMask: 331 },
  { name: '정태현', form: 4, magicId: 0, pitchMask: 32811 },
  { name: '오수환', form: 0, magicId: 0, pitchMask: 77 },
  { name: '임창영', form: 2, magicId: 0, pitchMask: 11393 },
  { name: '다이스케', form: 1, magicId: 0, pitchMask: 2245 },
  { name: '유우', form: 3, magicId: 0, pitchMask: 4387 },
  { name: '히사시', form: 4, magicId: 0, pitchMask: 16531 },
  { name: '큐지', form: 2, magicId: 0, pitchMask: 141 },
  { name: '타카히로', form: 0, magicId: 0, pitchMask: 209 },
  { name: '히데키', form: 2, magicId: 0, pitchMask: 16905 },
  { name: '마사히로', form: 3, magicId: 0, pitchMask: 1073 },
  { name: '토시야', form: 5, magicId: 0, pitchMask: 32843 },
  { name: '아롤디스', form: 1, magicId: 0, pitchMask: 5441 },
  { name: '라조', form: 0, magicId: 0, pitchMask: 65619 },
  { name: '노르헤', form: 1, magicId: 0, pitchMask: 299 },
  { name: '이스멜', form: 0, magicId: 0, pitchMask: 16659 },
  { name: '시로', form: 1, magicId: 0, pitchMask: 301 },
  { name: '데니', form: 0, magicId: 0, pitchMask: 16531 },
  { name: '요렉시스', form: 0, magicId: 0, pitchMask: 333 },
  { name: '블라미르', form: 1, magicId: 0, pitchMask: 33297 },
  { name: '마이크', form: 0, magicId: 0, pitchMask: 82441 },
  { name: '사우저', form: 1, magicId: 0, pitchMask: 2849 },
  { name: '플로이드', form: 0, magicId: 0, pitchMask: 17681 },
  { name: '레스티', form: 0, magicId: 0, pitchMask: 69699 },
  { name: '페티드', form: 0, magicId: 0, pitchMask: 301 },
  { name: '베이커', form: 1, magicId: 0, pitchMask: 339 },
  { name: '올슨', form: 1, magicId: 0, pitchMask: 8469 },
  { name: '로저', form: 0, magicId: 0, pitchMask: 33353 },
  { name: '홍광기', form: 0, magicId: 0, pitchMask: 54273 },
  { name: '박재욱', form: 1, magicId: 0, pitchMask: 43521 },
  { name: '이규훈', form: 2, magicId: 0, pitchMask: 83973 },
  { name: '신동엽', form: 5, magicId: 0, pitchMask: 12419 },
  { name: '이종서', form: 1, magicId: 0, pitchMask: 10501 },
  { name: '박영덕', form: 0, magicId: 0, pitchMask: 70209 },
  { name: '이규훈', form: 3, magicId: 0, pitchMask: 849 },
  { name: '신동엽', form: 4, magicId: 0, pitchMask: 33833 },
]
